# Generated by Django 5.1.2 on 2024-10-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ['-actual_time'], 'verbose_name': 'Task Execution Log', 'verbose_name_plural': 'Task Execution Logs'},
        ),
    ]
